add_test([=[BITTest.PrefixSum]=]  /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests/test_BIT [==[--gtest_filter=BITTest.PrefixSum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BITTest.PrefixSum]=]  PROPERTIES WORKING_DIRECTORY /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BITTest.RangeSum]=]  /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests/test_BIT [==[--gtest_filter=BITTest.RangeSum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BITTest.RangeSum]=]  PROPERTIES WORKING_DIRECTORY /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BITTest.UpperBound]=]  /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests/test_BIT [==[--gtest_filter=BITTest.UpperBound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BITTest.UpperBound]=]  PROPERTIES WORKING_DIRECTORY /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BITTest.BoundaryCases]=]  /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests/test_BIT [==[--gtest_filter=BITTest.BoundaryCases]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BITTest.BoundaryCases]=]  PROPERTIES WORKING_DIRECTORY /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BITTest.LargeRandomData]=]  /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests/test_BIT [==[--gtest_filter=BITTest.LargeRandomData]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BITTest.LargeRandomData]=]  PROPERTIES WORKING_DIRECTORY /Users/yiranwu1997/CLionProjects/cp-templates-cpp/build_tests/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_BIT_TESTS BITTest.PrefixSum BITTest.RangeSum BITTest.UpperBound BITTest.BoundaryCases BITTest.LargeRandomData)
